creation_rules:
  - pgp: '30B1 28A6 8534 A766 A646  DCDF D1E7 6CE1 660D 14D6'
    path_regex: -gpg\.
  - age: 'age1s3rr0xyt337vcfdhgsqhcd587vrlwzzgvtl2v6kya3ex5m0vg9wqz3l9ld'
    path_regex: -age\.
  - hc_vault_transit_uri: "https://vault.wolke8.it/v1/transit/keys/argocd"
    # encrypted_regex: '^(user.*|pass.*|.*[Bb]earer.*|salt|sentry.*|.*[Tt]oken|roleid|secretid)$'