apiVersion: v2
name: nginx-secret-content
description: testapp for encryption in argocd

type: application
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.21.6


dependencies: # A list of the chart requirements (optional)
  - name: nginx
    version: "9.8.0"
    repository: https://charts.bitnami.com/bitnami
    # condition: (optional) A yaml path that resolves to a boolean, used for enabling/disabling charts (e.g. subchart1.enabled )
    # tags: # (optional)
    #   - Tags can be used to group charts for enabling/disabling together
    # import-values: # (optional)
    #   - ImportValues holds the mapping of source values to parent key to be imported. Each item can be a string or pair of child/parent sublist items.
    # alias: (optional) Alias to be used for the chart. Useful when you have to add the same chart multiple times