# legt den Transit-Vault nach dem starten an

# echo starting;
# apk update; apk add curl;
# until $(curl --output /dev/null --silent --head --fail ${VAULT_ADDR}); do
#     printf '.'
#     sleep 5
# done;
# echo done;

# vault secrets enable transit;
# vault write -f transit/keys/argocd;


apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: in-cluster-vault-transit-setup
  namespace: argocd
spec:
  project: default
  source:

    helm:
      valueFiles:
        - values.yaml
    repoURL: https://github.com/realestatepilot/argocd-testbed.git
    targetRevision: argocd-2.8
    path: "helm-charts/vault-transit-setup"

    # helm:
    #   values: |
    #     image:
    #       repository: hashicorp/vault
    #       pullPolicy: IfNotPresent
    #       # Overrides the image tag whose default is the chart appVersion.
    #       tag: "1.14"      
    #     securityContext:
    #       runAsNonRoot: true
    #       runAsUser: 999
    #       capabilities:
    #         add: ["IPC_LOCK"]

    #     command: ["/bin/sh", "-c"]
    #     args:
    #       - sleep infinity;
    #     env:
    #       - name: VAULT_ADDR
    #         value: http://in-cluster-vault:8200
    #       - name: VAULT_TOKEN
    #         value: mySecret

    # repoURL: https://realestatepilot.github.io/helm-charts
    
    # targetRevision: 0.1.9
    # chart: generic
    
  destination:
    name: in-cluster
    namespace: vault

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
